name: Example pipeline
on:
 pull_request:
   branches: [master]

permissions:
 id-token: write
 contents: read

jobs:
 pull_request:
   runs-on: ubuntu-latest

   env:
     AWS_DEFAULT_REGION: ap-south-1

   steps:
   - name: configureawscredentials
     uses: aws-actions/configure-aws-credentials@master
     with:
       role-to-assume: arn:aws:iam::539994560210:role/AWS_INFRA_Role
       role-session-name: samplerolesession
       aws-region: ${{env.AWS_DEFAULT_REGION}}

   - name: Checkout
     uses: actions/checkout@master

   - name: Some AWS commands
     run: |
       aws --region ap-south-1 ……
