name: My Deployment
on:
  push:
    branches:
      - master
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: ap-south-1
          role-to-assume: arn:aws:iam::539994560210:role/AWS_INFRA_Role
          role-session-name: GitHubActions
      - name: Run Terraform commands
        run: |
          terraform init
          terraform apply -auto-approve
          terraform destroy -auto-approve


      
